// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


var HelloWorld_test = 0;

var HelloWorld = 0;

exports.HelloWorld_test = HelloWorld_test;
exports.HelloWorld = HelloWorld;
/* No side effect */
